"""Provider contracts for OCR, LLM, and future external AI adapters."""

from app.providers.base import (
    AIProvider,
    AIProviderMetadata,
    AIProviderRunContext,
    ProviderCapability,
    ProviderDeploymentMode,
    ProviderHealthCheck,
    ProviderHealthStatus,
)
from app.providers.errors import (
    ProviderConfigurationError,
    ProviderDependencyError,
    ProviderError,
    ProviderExecutionError,
    ProviderPrivacyPolicyError,
    ProviderPromptError,
    ProviderStructuredOutputValidationError,
)
from app.providers.llm import (
    LLMGenerationRequest,
    LLMGenerationResult,
    LLMMessage,
    LLMMessageRole,
    LLMProvider,
    LLMProviderRunContext,
    LLMResponseFormat,
)
from app.providers.local_ocr import (
    ChandraOCRProvider,
    PaddleOCRProvider,
    TesseractOCRProvider,
)
from app.providers.mock import (
    DEFAULT_MOCK_OCR_TEXT,
    DEFAULT_STRUCTURED_OUTPUTS,
    MOCK_PROVIDER_VERSION,
    MockLLMProvider,
    MockOCRProvider,
)
from app.providers.ocr import (
    OCRExtractionMode,
    OCRInput,
    OCRProvider,
    OCRProviderRunContext,
    OCRRequestOptions,
    OCRResult,
    OCRTextBlock,
)
from app.providers.ollama import OllamaLLMProvider
from app.providers.openai import OpenAIResponsesLLMProvider
from app.providers.privacy import (
    ProviderDataSensitivity,
    ProviderDataUseCase,
    ProviderPrivacyAction,
    ProviderPrivacyContext,
    ProviderPrivacyDecision,
    ProviderPrivacyGate,
    ProviderPrivacyPolicy,
    ProviderRedactionResult,
    build_provider_privacy_policy,
    redact_and_minimize_text,
)
from app.providers.prompts import (
    DEFAULT_PROMPT_REGISTRY,
    PromptMessageTemplate,
    PromptRegistry,
    PromptRenderResult,
    PromptSpec,
    build_default_prompt_registry,
    render_template,
)
from app.providers.routing import (
    LLMProviderInvocationResult,
    OCRProviderInvocationResult,
    ProviderModelRoute,
    ProviderRouteKind,
    ProviderRoutingConfig,
    ProviderRuntime,
    ProviderRuntimePolicy,
    ProviderTaskType,
    ProviderUsageCost,
    build_default_provider_routing_config,
    estimate_llm_cost,
)
from app.providers.structured_output import (
    DEFAULT_STRUCTURED_OUTPUT_SCHEMAS,
    StructuredOutputValidationResult,
    is_registered_output_schema,
    parse_and_validate_structured_output,
    validate_structured_output,
)

__all__ = [
    "AIProvider",
    "AIProviderMetadata",
    "AIProviderRunContext",
    "ProviderCapability",
    "ProviderDeploymentMode",
    "ProviderHealthCheck",
    "ProviderHealthStatus",
    "LLMGenerationRequest",
    "LLMGenerationResult",
    "LLMMessage",
    "LLMMessageRole",
    "LLMProvider",
    "LLMProviderRunContext",
    "LLMResponseFormat",
    "DEFAULT_MOCK_OCR_TEXT",
    "DEFAULT_STRUCTURED_OUTPUTS",
    "ChandraOCRProvider",
    "MOCK_PROVIDER_VERSION",
    "MockLLMProvider",
    "MockOCRProvider",
    "OCRExtractionMode",
    "OCRInput",
    "OllamaLLMProvider",
    "OpenAIResponsesLLMProvider",
    "OCRProvider",
    "OCRProviderRunContext",
    "OCRRequestOptions",
    "OCRResult",
    "OCRTextBlock",
    "PaddleOCRProvider",
    "ProviderConfigurationError",
    "ProviderDependencyError",
    "ProviderError",
    "ProviderExecutionError",
    "ProviderPrivacyPolicyError",
    "ProviderPromptError",
    "ProviderStructuredOutputValidationError",
    "TesseractOCRProvider",
    "DEFAULT_PROMPT_REGISTRY",
    "DEFAULT_STRUCTURED_OUTPUT_SCHEMAS",
    "PromptMessageTemplate",
    "PromptRegistry",
    "PromptRenderResult",
    "PromptSpec",
    "LLMProviderInvocationResult",
    "OCRProviderInvocationResult",
    "ProviderModelRoute",
    "ProviderRouteKind",
    "ProviderRoutingConfig",
    "ProviderRuntime",
    "ProviderRuntimePolicy",
    "ProviderTaskType",
    "ProviderUsageCost",
    "ProviderDataSensitivity",
    "ProviderDataUseCase",
    "ProviderPrivacyAction",
    "ProviderPrivacyContext",
    "ProviderPrivacyDecision",
    "ProviderPrivacyGate",
    "ProviderPrivacyPolicy",
    "ProviderRedactionResult",
    "StructuredOutputValidationResult",
    "build_default_provider_routing_config",
    "build_default_prompt_registry",
    "build_provider_privacy_policy",
    "estimate_llm_cost",
    "is_registered_output_schema",
    "parse_and_validate_structured_output",
    "redact_and_minimize_text",
    "render_template",
    "validate_structured_output",
]
